datasets:
  strongreject_small:
    path: "data/evaluation/strongreject/strongreject_small_dataset.csv"
    column: "question"

    
models:
  Llama-2-7b-chat-hf: "models/meta-llama/Llama-2-7b-chat-hf"
  llama_lora_h10: "results/E3/A/adapter"